version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: fleetpulse-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=fleetpulse
      - DOCKER_INFLUXDB_INIT_ORG=fleetpulse
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=fleetpulse-dev-token
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
    volumes:
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: fleetpulse-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  influxdb-data:
  redis-data:
